/** Edge/API response and email copy. Protocol values intentionally remain with transport code. */
export const ApiStringResources = {
  rateLimited: 'Too many requests. Please try again later.',
  authClientIdMissing: 'GITHUB_CLIENT_ID is not configured in Cloudflare environment variables.',
  authorizationCodeMissing: 'Missing authorization code from GitHub',
  authCredentialsMissing: 'GITHUB_CLIENT_ID or GITHUB_CLIENT_SECRET is missing from Cloudflare environment.',
  oauthStateInvalid: 'Invalid or missing OAuth state token (CSRF check failed).',
  oauthCodeInvalid: 'Invalid authorization code',
  methodNotAllowed: 'Method Not Allowed',
  unsupportedContentType: 'Unsupported Content-Type. Must be application/json.',
  payloadTooLarge: 'Payload exceeds maximum allowed limit (10KB).',
  maliciousPayload: 'Malicious payload detected: Prototype pollution attempt rejected.',
  botVerificationFailed: 'Bot verification failed. Please try again.',
  emailGatewayMissing: 'Email gateway configuration missing. Please email founder@ai-borne.in directly.',
  emailDeliveryFailed: 'Failed to deliver support email. Please email founder@ai-borne.in directly.',
  emailGatewayUnavailable: 'Failed to connect to email gateway. Please email founder@ai-borne.in directly.',
  supportMessageSent: 'Thank you! Your message has been sent successfully.',
  emailRequired: 'Email address is required.',
  emailTooLong: 'Email address exceeds maximum length of 100 characters.',
  emailInvalid: 'Invalid email address format.',
  messageTooShort: 'Support message must be at least 5 characters long.',
  messageTooLong: 'Support message exceeds maximum length of 3000 characters.',
  contactEmailSubject: '[AI-Borne Web Support] New message from',
  autoReplySubject: '[AI-Borne Support] We received your message',
} as const;
